Add a new beacon example
meow-edit/meow pull request #248
Opened 2022-05-16 08:33 UTC by zhscn

2022-05-16 19:46 UTC, eshrh requested changes
why do you think we need this in addition to the other two? in my opinion, it would be cool if you could show some of the deeper features of beacon, like meow-swap-grab or something as well.

2022-05-16 19:46 UTC, eshrh commented on meow-tutor.el
> + 2. Select the whole region with \\[meow-line]
You need to press 3 after a single meow-line to select the whole region

2022-05-16 19:46 UTC, eshrh commented on meow-tutor.el
> + 10. Press \\[meow-end-or-call-kmacro] to end macro recording and apply to all fake cursors
Need to press meow-grab again to exit beacon

2022-05-16 19:46 UTC, eshrh commented on meow-tutor.el
> + 6. Press \\[move-beginning-of-line] to move cursor to beginning of current line
Instead you can just negative find backwards to the ( character.

2022-05-17 02:13 UTC, zhscn commented
> why do you think we need this in addition to the other two? in my opinion, it would be cool if you could show some of the deeper features of beacon, like meow-swap-grab or something as well.

Yes, there is no deeper feature, the major idea is using kmacro in beacon, which is introduced in Ex A

> Instead you can just negative find backwards to the ( character.

The result is not what we expect, since every line has multiple ( characters, negative finding will append text on after ( characters.

The correct method is that create a new kmacro and apply it to every line, so `meow-kmacro-lines` also works.

Maybe we need to introduce `meow-find-first` or other helper commands to avoid calling kmacro manually.

---

Actually this example is from https://github.com/meow-edit/meow/blob/master/EXPLANATION.org#case-3 ,

2022-05-17 02:33 UTC, zhscn commented
Maybe this snippet is not an ideal example, but I think [EXPLANATION.org#case-3](https://github.com/meow-edit/meow/blob/master/EXPLANATION.org#case-3) should be introduced in tutor

2022-05-17 02:33 UTC, closed without merging